---
title: "Présence des oiseaux dans les Alpes françaises"
author: "___"
date: "__/__/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
SciViews::R

# chargement de fonction spécifique 
source("../R/carto.R")
```

<!--- Consignes
Si cela est nécessaire, ajoutez d'autres scripts comprenant des fonctions utiles.
--->


# Introduction

Des scientifiques ont étudié la présence de 19 espèces d'oiseaux dans 23 régions des Alpes françaises. La carte ci-dessous présente la régions étudiées. 

```{r}
read("../data/atlas_map.rds") %>.%
  sf::st_as_sf(.) %>.%
  chart(., ~ 0 %label=% names) +
  geom_sf() +
  geom_sf_text(size = 2) +
  ggsn::blank() 
```
Des relevés de températures et de précipitations ont été réalisée dans chaque station. 

# Analyse

## Méteo

<!--- Consignes
Importez le tableau de données atlas_meteo.csv. Ce tableau comprend les valeurs minimales de température et les valeurs maximales de température en janvier et en juillet pour chaque station. Il comprend aussi des informations sur les précipitations.
--->

```{r meteo}

```

<!--- Consignes
Réalisez un graphique pertinent pour mettre en avant les corrélations linéaires entre les variables de ce tableau. Décrivez ce graphique en maximum 3 phrases.
--->

```{r meteoplot}

```

## Recensement des oiseaux

<!--- Consignes
Importez le tableau de données atlas_birds.csv. Ce tableau comprend des informations sur le recensement d'oiseaux. 

Astuces : Les mesures ne sont pas des dénombrements simples. Les valeurs varient entre 0 et 4. 0 étant l'absence de l'espèce et 4 présence accrue de l'espèce.
--->

```{r birds}

```

<!--- Consignes
Réalisez un graphique pertinent pour mettre en avant la distribution des espèces dans les différentes stations. Ce graphique doit être adapté à des données semi-qualitative. Décrivez ce graphique en maximum 3 phrases.
--->

```{r birdsplot}

```

## Analyse factorielle multiple

<!--- Consignes
Combinez vos tableaux relatifs aux données météorologiques et aux données de présences des oiseaux d'intérêts.
--->

```{r bind}

```

<!--- Consignes
Réalisez votre AFM. Réalisez ensuite un résumé de votre objet atlas_mfa. Décrivez votre résultat en 2 phrases maximum.
--->

```{r mfa}
atlas_mfa <- mfa()
summary(atlas_mfa)
```

<!--- Consignes
Réalisez le graphique des éboulis. Décrivez votre résultat en 2 phrases maximum.
--->

```{r mfa_scree}

```

<!--- Consignes
Réalisez le graphique de la répartition des variables dans l'espace. Décrivez votre résultat en 5 phrases maximum.
--->

```{r mfa_loadings}

```


<!--- Consignes
Réalisez le graphique de la répartition des composantes princiaples dans l'espace. Décrivez votre résultat en 3 phrases maximum.
--->

```{r mfa_axes}

```

<!--- Consignes
Réalisez le graphique de la répartition des individus dans l'espace. Décrivez votre résultat en 3 phrases maximum.
--->

```{r mfa_axes}

```

<!--- Consignes
Sur base de la série de graphique que vous venez de réaliser, réalisez une description globale des stations en fonction des conditions météo et de la présence des oiseaux étudiés en maximum 5 phrases.
--->

`
