---
title: "Open Data"
author: '...'
date: "3/29/2020"
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Objectif

Suite à la lecture de la section sur la gestion des données avec le principe *FAIR*. Rédigez un document de synthèse de *maximum 3 pages* au format pdf qui critique votre plan de gestion des données réalisée dans le cadre des données obtenues sur la biométrie humaine. Cette critique doit répondre à 2 questions :

- Quelles sont les bonnes pratiques que vous avez employées ? 
- Quels sont les éléments que vous devriez améliorer à l'avenir dans un prochain plan de gestion des données ? 

Dans le cadre du cours de science des données biologiques I, vous avez donc du concevoir un plan d’expérience afin d’acquérir des données. Etant donnée que vous avez été des scientifiques consciencieux, vous avez collecté vos données en y associant des métadonnées.

Les données ont été collectée via un document googlesheet dont l’url est le suivant:

- <https://docs.google.com/spreadsheets/d/1GJAGWjwNBtEGqQXqFcNxkrwcw-5n-gqwmiGAzxUZrxg/edit?usp=sharing>

Les métadonnées associées aux données ont été recensées dans un document googledoc dont l’url est le suivant:

- <https://docs.google.com/spreadsheets/d/1j55bB9YEAVbS4eRE-i6L-NEYhHXua-dxs-aQr_qko7k/edit?usp=sharing>

# Critique de la gestion de données
